//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Order
    {
        public int OrderId { get; set; }
        public string EmailId { get; set; }
        public string OrderNumber { get; set; }
        public string BrandName { get; set; }
        public string ProductName { get; set; }
        public string RAMName { get; set; }
        public string ROMName { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }

        public string ErrorMessage { get; set; }
    
        public virtual Tbl_LoginAndRegister Tbl_LoginAndRegister { get; set; }
    }
}
