//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileStoreApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Tbl_DisplayImage
    {
        public int SNo { get; set; }
        public Nullable<int> BrandId { get; set; }
        public string BrandName { get; set; }
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> RAMId { get; set; }
        public string RAMName { get; set; }
        public Nullable<int> ROMId { get; set; }
        public string ROMName { get; set; }
        public Nullable<int> ProcessorId { get; set; }
        public string ProcessorName { get; set; }
        public string ImagePath { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Quantity { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
